freebsd_instance:
  image_family: freebsd-12-2

task:
  install_script:
    - pkg update
    - pkg upgrade -y
    - pkg install -y git gmake pkgconf e2fsprogs-libuuid sqlite3 gtkmm30 cppzmq libgit2 boost-libs glm opencascade podofo libzip gtksourceviewmm3
  script:
    - ls
    - clang --version
    - gmake -j2
