name: Stylecheck and CI

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  stylecheck:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install preliminary dependencies
      run: sudo apt-get update -y && sudo apt-get install curl gnupg apt-transport-https -y
    - name: Add clang 9.0 to apt sources
      run: echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main" | sudo tee -a /etc/apt/sources.list
    - name: Add LLVM apt key
      run: curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    - name: Install dependencies
      run: sudo apt-get update -y && sudo apt-get install git clang-format-9 -y
    - name: Style checker
      run: bash scripts/stylecheck.sh

  build:
    runs-on: ubuntu-latest
    container: debian:buster
    needs: stylecheck
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: apt-get update -y && apt-get install git build-essential libsqlite3-dev util-linux librsvg2-dev libcairomm-1.0-dev libepoxy-dev libgtkmm-3.0-dev uuid-dev libboost-dev  libzmq5 libzmq3-dev libglm-dev libgit2-dev libcurl4-gnutls-dev liboce-ocaf-dev libpodofo-dev python3-dev libzip-dev git -y
    - name: Check version
      run: python3 check_version.py
    - name: Build
      run: make -j2 LDFLAGS="-lstdc++fs -lpthread"

  build-pr-review:
    runs-on: ubuntu-latest
    container: debian:bullseye
    needs: stylecheck
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: apt-get update -y && apt-get install git build-essential libsqlite3-dev util-linux librsvg2-dev libcairomm-1.0-dev libepoxy-dev libgtkmm-3.0-dev uuid-dev libboost-dev  libzmq5 libzmq3-dev libglm-dev libgit2-dev libcurl4-gnutls-dev liboce-ocaf-dev libpodofo-dev python3-dev libzip-dev git libosmesa6-dev -y
    - name: Build
      run: make -j2 build/horizon-pr-review

  build-clang:
    runs-on: ubuntu-latest
    container: debian:buster
    needs: stylecheck
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: apt-get update -y && apt-get install git build-essential clang libsqlite3-dev util-linux librsvg2-dev libcairomm-1.0-dev libepoxy-dev libgtkmm-3.0-dev uuid-dev libboost-dev  libzmq5 libzmq3-dev libglm-dev libgit2-dev libcurl4-gnutls-dev liboce-ocaf-dev libpodofo-dev python3-dev libzip-dev git -y
    - name: Check version
      run: python3 check_version.py
    - name: Build
      run: make -j2 CXX=clang LDFLAGS='-lstdc++ -lm -lpthread -lstdc++fs'

  build-ubuntu:
    runs-on: ubuntu-18.04
    needs: stylecheck
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update -y && sudo apt-get install git build-essential g++-8 libsqlite3-dev util-linux librsvg2-dev libcairomm-1.0-dev libepoxy-dev libgtkmm-3.0-dev uuid-dev libboost-dev  libzmq5 libzmq3-dev libglm-dev libgit2-dev libcurl4-gnutls-dev liboce-ocaf-dev libpodofo-dev python3-dev libzip-dev git -y
    - name: Build
      run: make -j2 CXX=g++-8 CC=gcc-8 WARNFLAGS="-Wall -Wshadow -Wno-parentheses" 

  build-debug:
    runs-on: ubuntu-latest
    container: debian:buster
    needs: stylecheck
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: apt-get update -y && apt-get install git build-essential libsqlite3-dev util-linux librsvg2-dev libcairomm-1.0-dev libepoxy-dev libgtkmm-3.0-dev uuid-dev libboost-dev  libzmq5 libzmq3-dev libglm-dev libgit2-dev libcurl4-gnutls-dev liboce-ocaf-dev libpodofo-dev python3-dev libzip-dev git -y
    - name: Build
      run: make DEBUG=1 LDFLAGS="-lstdc++fs -lpthread" -j2

  build-py:
    runs-on: ubuntu-latest
    container: debian:buster
    needs: stylecheck
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: apt-get update -y && apt-get install git build-essential libsqlite3-dev util-linux librsvg2-dev libcairomm-1.0-dev libepoxy-dev libgtkmm-3.0-dev uuid-dev libboost-dev  libzmq5 libzmq3-dev libglm-dev libgit2-dev libcurl4-gnutls-dev liboce-ocaf-dev libpodofo-dev python3-dev libzip-dev git python3-cairo-dev libosmesa6-dev -y
    - name: Install pyyaml for version check
      run: apt-get install -y python3-yaml
    - name: Build
      run: make -j2 build/horizon.so LDFLAGS=-lstdc++fs
    - name: Test python module
      run: python3 -c 'import sys; sys.path.append("build"); import horizon'
    - name: Check app versions
      run: python3 scripts/check_app_versions.py

  build-py-ubuntu:
    runs-on: ubuntu-18.04
    needs: stylecheck
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update -y && sudo apt-get install git build-essential g++-8 libsqlite3-dev util-linux librsvg2-dev libcairomm-1.0-dev libepoxy-dev libgtkmm-3.0-dev uuid-dev libboost-dev  libzmq5 libzmq3-dev libglm-dev libgit2-dev libcurl4-gnutls-dev liboce-ocaf-dev libpodofo-dev python3-dev libzip-dev git python3-cairo-dev libosmesa6-dev -y
    - name: Build
      run: make -j2 build/horizon.so CXX=g++-8 CC=gcc-8
    - name: Test python module
      run: python3 -c 'import sys; sys.path.append("build"); import horizon'
