name: Build Windows binaries

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build-win32:
    runs-on: windows-latest
    steps:
    - name: Check tag
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "Building tag ${{ github.ref }}"
    - uses: actions/checkout@v2
    - uses: numworks/setup-msys2@v1
      with:
        msystem: MINGW64
    - name: Install updates
      run: |
        msys2do pacman -Syu --noconfirm
        msys2do pacman -Syu --noconfirm
    - name: Install dependencies
      shell: cmd
      run: msys2do pacman -S --noconfirm --needed mingw-w64-x86_64-gcc mingw-w64-x86_64-{gcc,gtkmm3,boost,sqlite3,toolchain,zeromq,glm,libgit2,oce,podofo,libzip} zip make git dos2unix
    - name: Build
      run: msys2do make -j2
    - name: Make dist
      run: msys2do bash ./make_bindist.sh -n
    - name: Check for missing DLLs
      run: msys2do bash ./check_dll.sh
    - name: set artifact name
      shell: bash
      run: echo "::set-env name=artifact_name::horizon-win64-$(date +%Y-%m-%d-%H%M)"
    - uses: actions/upload-artifact@v2-preview
      with:
        name: ${{ env.artifact_name }}
        path: dist/
    - name: Build MSI
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        $env:PATH += ";$($Env:WIX)\bin"
        cd wix
        .\install.bat
    - uses: actions/upload-artifact@v2-preview
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: horizon-win64-installer
        path: wix/*.msi
