name: Build Windows binaries

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build-win32:
    runs-on: windows-latest
    steps:
    - name: Check tag
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "Building tag ${{ github.ref }}"
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-pkgconf
          mingw-w64-x86_64-gtkmm3
          mingw-w64-x86_64-boost
          mingw-w64-x86_64-sqlite3
          mingw-w64-x86_64-zeromq
          mingw-w64-x86_64-glm
          mingw-w64-x86_64-libgit2
          mingw-w64-x86_64-oce
          mingw-w64-x86_64-podofo
          mingw-w64-x86_64-libzip
          zip
          make
          git
          dos2unix
    - name: Build
      shell: msys2 {0}
      run: make -j2 WARNFLAGS="-Wall -Wshadow -Wno-attributes"
    - name: Make dist
      shell: msys2 {0}
      run: ./make_bindist.sh -n
    - name: Check for missing DLLs
      shell: msys2 {0}
      run: ./check_dll.sh
    - name: set artifact name
      shell: msys2 {0}
      run: echo "artifact_name=horizon-win64-$(date +%Y-%m-%d-%H%M)" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v2-preview
      with:
        name: ${{ env.artifact_name }}
        path: dist/
    - name: Build MSI
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        $env:PATH += ";$($Env:WIX)\bin"
        cd wix
        .\install.bat
    - uses: actions/upload-artifact@v2-preview
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: horizon-win64-installer
        path: wix/*.msi
